apiVersion: v1
kind: Service
metadata:
    name: "automlaks-dd40"
    labels:
        app: "automlaks-dd40"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "automlaks-dd40"