on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: madvisorautoml.azurecr.io
        username: ${{ secrets.acr_madvisorautoml_username }}
        password: ${{ secrets.acr_madvisorautoml_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t madvisorautoml.azurecr.io/automlaks:${{ github.sha }}
        docker push madvisorautoml.azurecr.io/automlaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_automlaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep automlaks865a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace automlaks865a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: automlaks865a
        container-registry-url: madvisorautoml.azurecr.io
        container-registry-username: ${{ secrets.acr_madvisorautoml_username }}
        container-registry-password: ${{ secrets.acr_madvisorautoml_password }}
        secret-name: automlaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: automlaks865a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          madvisorautoml.azurecr.io/automlaks:${{ github.sha }}
        imagepullsecrets: |
          automlaksdockerauth